<template>
  <body>

    <div>
      <button id="homescreenButtonTopLeft" v-on:click="exitCreatorMode">{{ uiLabels.exit }}</button>
      <button id="UKflagga" v-on:click="switchLanguageEnglish">{{ uiLabels.changeLanguage }}</button>
      <button id="sverigeflagga" v-on:click="switchLanguageSwedish">{{ uiLabels.changeLanguage }}</button>
    </div>

    <header>
      <h1> {{ uiLabels.createInfoTitle }} </h1>
    </header>

    <main>
      <!--gör array i labels som man loopar över, för mycket kladd slay-->
      <div>
        <ol>
          <li v-for="(instruction, index) in uiLabels.createInfo" :key="index">
            {{ instruction }}
          </li>
        </ol>
      </div>

      <div>
        <p>Jeopardy ID:</p>
        <p style="font-size: 2em;">{{ autoPollId }}</p>
      </div>

      <div>
        <p>{{ uiLabels.numberCategories }}:</p>
        <input type="number" v-model="categoryNo" min=1 step=1>
      </div>

      <div>
        <p>{{ uiLabels.numberQuestions }}:</p>
        <input type="number" v-model="questionNo" min=1 step=1>
      </div>

      <div>
        <button v-on:click="createPoll">
          {{ uiLabels.createPoll }}
        </button>
        <p v-if="errorIdMessage == true" style="color: red">
          {{ uiLabels.errorCreateIdMessage }}
        </p>
        <p v-if="errorCategoryNo == true" style="color: red">
          {{ uiLabels.errorCreateCategoryMessage }}
        </p>
        <p v-if="errorQuestionNo == true" style="color: red">
          {{ uiLabels.errorCreateQuestionMessage }}
        </p>
      </div>

      <!-- Knappar för autoGenerateQuiz -->
      <div>
        <p>{{ uiLabels.quizTopic }}:</p>
        <input type="text" v-model="quizTopic">
      </div>
      <div>
        <div class="button-container">
          <button v-on:click="autoGenerateQuiz" :disabled="isButtonDisabled">
            {{ autoGenerateButtonText }}
          </button>
          <button @click="toggleInfoText" class="info-button">?</button>
        </div>
        <p class="error-message">{{ autoErrorMessage }}</p>
        <p v-if="showInfoText" class="info-text-container">{{ uiLabels.quizGenerationInfoText }}</p>
      </div>

    </main>
  </body>
</template>

<script>
// Importing components and libraries
import ResponsiveNav from '@/components/ResponsiveNav.vue';
import io from 'socket.io-client';
const socket = io(sessionStorage.getItem("ipAdressSocket"));

export default {
  // Component name and imported components
  name: 'JCreateInfo',
  components: {
    ResponsiveNav
  },

  // Initial data properties
  data: function () {
    return {
      uiLabels: {}, // Object for storing UI labels
      autoGenerateButtonText: "",
      pollId: "", // Input for poll ID
      lang: localStorage.getItem("lang") || "en", // Language setting
      errorIdMessage: false,
      errorCategoryNo: false,
      errorQuestionNo: false,
      categoryNo: 5,
      questionNo: 5,
      autoPollId: "",
      quizTopic: "",
      autoErrorMessage: "",
      isButtonDisabled: false,
      showInfoText: false,
    }
  },

  // Lifecycle hook - component creation
  created: function () {
    // Lifecycle hook - component creation
    // this.id = this.$route.params.id;

    // Emit an event to the server when the page is loaded
    socket.emit("pageLoaded", this.lang);

    // Emit an event to update and fetch the J Poll ID 
    socket.emit("updateAutoPollId");

    // Listen for initialization data from the server
    socket.on("init", (labels) => {
      this.uiLabels = labels
      this.autoGenerateButtonText = this.uiLabels.autoGenerateQuiz;
    });

    // Listen for the event where the pollId is updated
    socket.on("autoPollIdUpdated", (autoPollId) =>
      this.autoPollId = autoPollId
    )

    socket.on("autoGeneratedQuizAutoGenerated", () => {
      console.log("autoGeneratedQuizAutoGenerated jcreateinfo");
      this.isButtonDisabled = false;
      this.$router.push('/BoardView/' + this.autoPollId);
    })

    socket.on('quizAutoGenerationError', () => {
      this.autoGenerateButtonText = this.uiLabels.autoGenerateQuiz;
      this.autoErrorMessage = this.uiLabels.quizGenerationError;
      this.isButtonDisabled = false;
    })


  },
  // Methods for language switching and toggling the navigation menu
  methods: {
    switchLanguageEnglish: function () {
      if (this.lang === "sv") {
        this.lang = "en"
      }
      localStorage.setItem("lang", this.lang);
      socket.emit("switchLanguage", this.lang)
    },
    switchLanguageSwedish: function () {
      if (this.lang === "en") {
        this.lang = "sv"
      }
      localStorage.setItem("lang", this.lang);
      socket.emit("switchLanguage", this.lang)
    },
    createPoll: function () {
      if (this.autoPollId !== "" && this.categoryNo > 0 && this.questionNo > 0) {
        this.errorIdMessage = false;
        this.errorCategoryNo = false;
        this.errorQuestionNo = false;
        socket.emit("createPoll", {
          pollId: this.autoPollId, lang: this.lang,
          questionNo: this.questionNo, categoryNo: this.categoryNo
        });
        this.$router.push('/BoardView/' + this.autoPollId);
      }
      if (this.pollId === "") {
        // this.errorIdMessage = true;
      }
      else {
        this.errorIdMessage = false;
      }

      if (this.categoryNo < 1 || this.categoryNo === "") {
        this.errorCategoryNo = true;
      }
      else {
        this.errorCategoryNo = false;
      }

      if (this.questionNo < 1 || this.questionNo === "") {
        this.errorQuestionNo = true;
      }
      else {
        this.errorQuestionNo = false;
      }
    },
    exitCreatorMode() {
      this.$router.push('/');
    },

    // Autogenerera quiz
    autoGenerateQuiz() {
      this.autoErrorMessage = "";
      this.autoGenerateButtonText = this.uiLabels.quizIsBeingGenerated;
      this.isButtonDisabled = true;
      const topic = this.quizTopic;

      socket.emit("autoGenerateQuiz", {
        pollId: this.autoPollId, lang: this.lang, topic: topic, questionNo: this.questionNo,
        categoryNo: this.categoryNo
      });
    },

    toggleInfoText() {
      this.showInfoText = !this.showInfoText;
    }
  }
}
</script>

<style scoped>
/* Scoped styles for the component */

ol {
  text-align: left;
  display: inline-block;
}

main {
  overflow: scroll;
}

.error-message {
  color: red;
}

.info-button {
  background-color: #073763ff;
  width: 5em;
  height: 4em;
  padding: 0;
  /* text-decoration: underline; */
  color: #ffff00;
  font-size: 1em;
}

.button-container {
  display: flex;
  justify-content: center;
  align-items: center;
}

.info-text-container {
  max-width: 600px;
  margin: 0 auto; 
  text-align: left;
}
</style>
